### LINK STATE ROUTING - DIJIKSTRA'S ALGORITHM

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\tharun\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: pytz>=2017.2 in c:\users\tharun\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\tharun\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\tharun\anaconda3\lib\site-packages (from pandas) (1.19.2)
Requirement already satisfied: six>=1.5 in c:\users\tharun\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [2]:
from pandas import DataFrame

In [3]:
graph = {'A':{'C':1,'B':3},
         'B':{'A':3,'C':7,'D':5,'E':1},
         'C':{'A':1,'B':7,'D':2},
         'D':{'B':5,'C':2,'E':7},
         'E':{'B':1,'D':7}
        }

nodes = list(graph.keys())
RoutingTable = []

for p,q in enumerate(nodes):

    visited = []
    unvisited = nodes.copy()
    next_node = len(nodes)*['']

    inf = float('inf')
    shortest_distance = len(nodes)*[inf]

    root_node = q
    current_node = q
    shortest_distance[ord(current_node)-65] = 0

    while True:
        for i in list(graph[current_node].keys()):
            if i not in visited:
                if shortest_distance[ord(current_node)-65]+graph[current_node][i] < shortest_distance[ord(i)-65]:
                    shortest_distance[ord(i)-65] = shortest_distance[ord(current_node)-65]+graph[current_node][i]
                    if current_node != root_node:
                        next_node[ord(i)-65] = current_node

        visited.append(current_node)
        unvisited.remove(current_node)

        if len(unvisited) == 0:
            break

        unvstd_aasci = [ord(x) for x in unvisited]
        min_value = min([shortest_distance[j-65] for j in unvstd_aasci])
        min_index = [j for j,x in enumerate(shortest_distance) if x == min_value]
        for j in min_index:
            if chr(65+j) in unvisited:
                current_node = chr(65+j)
                break

    for i in range(len(next_node)):
        if next_node[i] == root_node:
            next_node[i] = ''

    RoutingTable.append(DataFrame({'To':list(graph.keys()),'Cost':shortest_distance,'Next':next_node}))
    
    print(f"\n\nRouting table for {root_node}")
    display(RoutingTable[-1])

print(f"\n\nAvailable nodes ==> {nodes}")


start = input("\nEnter the start node : ")
while start not in nodes:
    print("Invalid Node....Try again")
    start = input("Enter the start node : ")
    
    
dest  = input("\nEnter the Destination node : ")
while dest not in nodes:
    print("Invalid Node....Try again")
    dest = input("Enter the Destination node : ")

    
index = ord(start)-65
df = RoutingTable[index]
path = []
path.append(start)
temp = dest
while df[df['To'] == temp]['Next'].values[0] != '':
    path.insert(1,df[df['To'] == temp]['Next'].values[0])
    temp = df[df['To'] == temp]['Next'].values[0]
    
print("\nOptimal path : ",end ="")
for i in range(len(path)):
    print(path[i],end = " ==> ")
print(dest)

Routing table for A

  To  Cost Next
0  A     0
1  B     3
2  C     1
3  D     3    C
4  E     4    B

Routing table for B

  To  Cost Next
0  A     3
1  B     0
2  C     4    A
3  D     5
4  E     1

Routing table for C

  To  Cost Next
0  A     1
1  B     4    A
2  C     0
3  D     2
4  E     5    B

Routing table for D

  To  Cost Next
0  A     3    C
1  B     5
2  C     2
3  D     0
4  E     6    B

Routing table for E

  To  Cost Next
0  A     4    B
1  B     1
2  C     5    A
3  D     6    B
4  E     0

Available nodes ==> ['A', 'B', 'C', 'D', 'E']

Enter the start node : f
Invalid Node....Try again
Enter the start node : C

Enter the Destination node : e
Invalid Node....Try again
Enter the Destination node : E

Optimal path : C ==> A ==> B ==> E

In [ ]:
sh